# -- 코드를 입력하세요
# select I.AUTHOR_ID, I.AUTHOR_NAME, I.CATEGORY, sum(J.SALES) from (SELECT * from BOOK A join AUTHOR B on A.AUTHOR_ID = B.AUTHOR_ID) I join BOOK_SALES J on I.BOOK_ID = J.BOOK_ID

select A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, sum(C.SALES*A.PRICE) AS TOTAL_SALES from BOOK A join AUTHOR B on A.AUTHOR_ID = B.AUTHOR_ID join BOOK_SALES C on A.BOOK_ID = C.BOOK_ID

WHERE YEAR(C.SALES_DATE) = "2022" AND MONTH(C.SALES_DATE) = "01"

group by A.AUTHOR_ID, A.CATEGORY

order by A.AUTHOR_ID, A.CATEGORY DESC