-- 코드를 입력하세요
select A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES from REST_INFO A join 
(SELECT FOOD_TYPE, MAX(FAVORITES) AS MAXFAVOR from REST_INFO group by FOOD_TYPE )
B on A.FOOD_TYPE = B.FOOD_TYPE

where A.FAVORITES = B.MAXFAVOR

order by A.FOOD_TYPE DESC

;

