-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, CONCAT(A.CITY," ", A.STREET_ADDRESS1," ", A.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTRING(A.TLNO,1,3), "-", SUBSTRING(A.TLNO,4,4), "-", SUBSTRING(A.TLNO, 8,4)) AS 전화번호
from USED_GOODS_USER as A join USED_GOODS_BOARD as B on A.USER_ID = B.WRITER_ID 


GROUP BY A.USER_ID having count(B.WRITER_ID) >= 3

order by A.USER_ID DESC;