select A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME from ANIMAL_INS A join ANIMAL_OUTS B on A.ANIMAL_ID = B.ANIMAL_ID


where (B.SEX_UPON_OUTCOME LIKE '%Spayed%' OR B.SEX_UPON_OUTCOME LIKE '%Neutered%') AND
A.SEX_UPON_INTAKE LIKE '%Intact%'

order by A.ANIMAL_ID