-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME from ANIMAL_INS A join ANIMAL_OUTS B on A.ANIMAL_ID = B.ANIMAL_ID

WHERE (A.SEX_UPON_INTAKE = "Intact Male" AND B.SEX_UPON_OUTCOME = "Neutered Male")
OR (A.SEX_UPON_INTAKE = "Intact Female" AND B.SEX_UPON_OUTCOME = "Spayed Female")
;