-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) as YEAR, MONTH(B.SALES_DATE) as MONTH, A.GENDER, count(DISTINCT(A.USER_ID)) as USERS from USER_INFO A join ONLINE_SALE B on A.USER_ID = B.USER_ID

where A.GENDER is not null

group by YEAR, MONTH, GENDER

order by YEAR, MONTH, GENDER