-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, sum(A.PRICE*B.AMOUNT) as TOTAL_SALES from FOOD_PRODUCT As A join FOOD_ORDER as B on A.PRODUCT_ID = B.PRODUCT_ID

where YEAR(B.PRODUCE_DATE)='2022' AND MONTH(B.PRODUCE_DATE) ='5' GROUP by PRODUCT_ID

order by TOTAL_SALES DESC, PRODUCT_ID;
