-- 코드를 입력하세요

SELECT REALTOTAL.FLAVOR FROM 

(
SELECT FH.FLAVOR, FH.TOTAL_ORDER as FHTO, JU.TOTAL_ORDER as JUTO from FIRST_HALF as FH join 

(Select FLAVOR, sum(TOTAL_ORDER)as TOTAL_ORDER from JULY group by FLAVOR ) as JU

on FH.FLAVOR = JU.FLAVOR
) as REALTOTAL

group by REALTOTAL.FLAVOR
order by REALTOTAL.FHTO + REALTOTAL.JUTO DESC
limit 3;
