-- 코드를 입력하세요
SELECT A.APNT_NO, C.PT_NAME, C.PT_NO, B.MCDP_CD, B.DR_NAME, A.APNT_YMD from APPOINTMENT A join DOCTOR B on A.MDDR_ID = B.DR_ID join PATIENT C on A.PT_NO = C.PT_NO
where
YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13 AND A.APNT_CNCL_YN = "N"

order by A.APNT_YMD