-- 코드를 입력하세요
SELECT A.WRITER_ID as USER_ID, B.NICKNAME, SUM(A.PRICE) as TOTAL_SALES from 
USED_GOODS_BOARD A join USED_GOODS_USER B on A.WRITER_ID = B.USER_ID

where A.STATUS = "DONE"

group by A.WRITER_ID, B.USER_ID

having TOTAL_SALES >= 700000 

order by TOTAL_SALES
;
