-- 코드를 입력하세요
select A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d')as REVIEW_DATE from MEMBER_PROFILE AS A join REST_REVIEW AS B on A.MEMBER_ID = B.MEMBER_ID where B.MEMBER_ID =(

SELECT A.MEMBER_ID FROM MEMBER_PROFILE  as A join REST_REVIEW as B on A.MEMBER_ID = B.MEMBER_ID 

group by A.MEMBER_ID
order by count(B.MEMBER_ID) DESC

limit 1
)

order by B.REVIEW_DATE, B.REVIEW_TEXT
;