-- 코드를 작성해주세요



select B.YEAR AS YEAR, abs(A.SIZE_OF_COLONY - B.MAX_SIZE) AS YEAR_DEV, A.ID from ECOLI_DATA as A join 
(
select YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY)AS MAX_SIZE 
from ECOLI_DATA 
group by YEAR(DIFFERENTIATION_DATE)
    ) as B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
    
    
    order by B.YEAR, YEAR_DEV;