-- 코드를 입력하세요
select DISTINCT A.CAR_ID from CAR_RENTAL_COMPANY_CAR AS A join CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B on A.CAR_ID = B.CAR_ID

where A.CAR_TYPE = '세단' AND MONTH(B.START_DATE) = '10'

ORDER BY A.CAR_ID DESC