# -- 코드를 작성해주세요

select sum(B.SCORE) as SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL from HR_EMPLOYEES A join HR_GRADE B  on A.EMP_NO = B.EMP_NO join HR_DEPARTMENT C on C.DEPT_ID = A.DEPT_ID

where B.YEAR = 2022

GROUP BY A.EMP_NO, A.EMP_NAME, A.POSITION
ORDER BY SCORE DESC
LIMIT 1;

