-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATE_DATE from
USED_GOODS_BOARD AS A join USED_GOODS_REPLY AS B on A.BOARD_ID = B.BOARD_ID
where A.CREATED_DATE BETWEEN '2022-10-01' and '2022-10-31'
order by B.CREATED_DATE ASC, A.TITLE;